name: vivafit_personal_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  android_intent_plus: ^5.2.0
  animated_toggle_switch: ^0.8.3
  carousel_slider: ^5.0.0
  carp_serializable: ^2.0.0
  cloud_firestore: ^5.4.4
  crypto: ^3.0.6
  dotted_dashed_line: ^0.0.3
  file_picker: ^8.1.3
  firebase_app_check: ^0.3.1+4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.4
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  health: ^11.1.0
  intl: ^0.19.0
  mime_type: ^1.0.1
  permission_handler: ^11.3.1
  provider: ^6.1.2
  readmore: ^3.0.0
  rxdart: ^0.28.0
  shared_preferences: ^2.3.2
  sign_in_with_apple: ^6.1.3
  simple_animation_progress_bar: ^1.8.2
  simple_circular_progress_bar: ^1.0.2  
  table_calendar: ^3.1.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/

fonts:
  - family: Poppins
    fonts:
      - asset: assets/font/Poppins-Regular.ttf
      - asset: assets/font/Poppins-Medium.ttf
        weight: 500
      - asset: assets/font/Poppins-Bold.ttf
        weight: 700
